# HOML CHAPTER 9

In [32]:
from sklearn.cluster import KMeans
from sklearn.datasets import make_blobs
import numpy as np
# extra code – the exact arguments of make_blobs() are not important
blob_centers = np.array([[ 0.2,  2.3], [-1.5 ,  2.3], [-2.8,  1.8],
                            [-2.8,  2.8], [-2.8,  1.3]])
blob_std = np.array([0.4, 0.3, 0.1, 0.1, 0.1])
X, y = make_blobs(n_samples=2000, centers=blob_centers, cluster_std=blob_std,
                    random_state=7)

k = 5
kmeans = KMeans(n_clusters=k, n_init=10, random_state=42)
y_pred = kmeans.fit_predict(X)

In [33]:
y_pred

array([0, 0, 4, ..., 3, 1, 0], shape=(2000,), dtype=int32)

In [34]:
y_pred is kmeans.labels_

True

In [35]:
kmeans.cluster_centers_

array([[-2.80214068,  1.55162671],
       [ 0.08703534,  2.58438091],
       [-1.46869323,  2.28214236],
       [-2.79290307,  2.79641063],
       [ 0.31332823,  1.96822352]])

In [36]:
X_new=np.array([[0, 2], [3, 2], [-3, 3], [-3, 2.5]])

In [37]:
kmeans.predict(X_new)

array([4, 4, 3, 3], dtype=int32)

In [38]:
kmeans.transform(X_new).round(2)

array([[2.84, 0.59, 1.5 , 2.9 , 0.31],
       [5.82, 2.97, 4.48, 5.85, 2.69],
       [1.46, 3.11, 1.69, 0.29, 3.47],
       [0.97, 3.09, 1.55, 0.36, 3.36]])

In [39]:
good_init = np.array([[-3, 3], [-3, 2], [-3, 1], [-1, 2], [0, 2]])
kmeans = KMeans(n_clusters=5, init=good_init, n_init=1, random_state=42)
kmeans.fit(X)

,n_clusters,5
,init,"array([[-3, ... [ 0, 2]])"
,n_init,1
,max_iter,300
,tol,0.0001
,verbose,0
,random_state,42
,copy_x,True
,algorithm,'lloyd'


In [40]:
kmeans.inertia_

211.5985372581684

In [41]:
kmeans.score(X)

-211.5985372581684

In [42]:
from sklearn.cluster import MiniBatchKMeans
minibatch_kmeans = MiniBatchKMeans(n_clusters=5, random_state=42)
minibatch_kmeans.fit(X)

c:\Users\uzebk\miniconda3\envs\dsenv\Lib\site-packages\sklearn\cluster\_kmeans.py:1955: UserWarning: MiniBatchKMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can prevent it by setting batch_size >= 2048 or by setting the environment variable OMP_NUM_THREADS=4
  warnings.warn(


,n_clusters,5
,init,'k-means++'
,max_iter,100
,batch_size,1024
,verbose,0
,compute_labels,True
,random_state,42
,tol,0.0
,max_no_improvement,10
,init_size,None
,n_init,'auto'


In [43]:
from sklearn.metrics import silhouette_score

In [44]:
silhouette_score(X,kmeans.labels_)

0.655517642572828

In [45]:
import PIL

In [46]:
from sklearn.datasets import load_digits
X_digits, y_digits = load_digits(return_X_y=True)
X_train, y_train = X_digits[:1400], y_digits[:1400]
X_test, y_test = X_digits[1400:], y_digits[1400:]

In [47]:
from sklearn.linear_model import LogisticRegression
n_labeled = 50
log_reg = LogisticRegression(max_iter=10_000)
log_reg.fit(X_train[:n_labeled], y_train[:n_labeled])

,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,None
,solver,'lbfgs'
,max_iter,10000
,multi_class,'deprecated'


In [48]:
log_reg.score(X_test, y_test)

0.7581863979848866

In [49]:
k = 50
kmeans = KMeans(n_clusters=k, n_init=10, random_state=42)
X_digits_dist = kmeans.fit_transform(X_train)
representative_digit_idx = X_digits_dist.argmin(axis=0)
X_representative_digits = X_train[representative_digit_idx]

c:\Users\uzebk\miniconda3\envs\dsenv\Lib\site-packages\sklearn\cluster\_kmeans.py:1419: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=6.
  warnings.warn(


In [50]:
y_representative_digits = np.array([
    1, 3, 6, 0, 7, 9, 2, 4, 8, 9,
    5, 4, 7, 1, 2, 6, 1, 2, 5, 1,
    4, 1, 3, 3, 8, 8, 2, 5, 6, 9,
    1, 4, 0, 6, 8, 3, 4, 6, 7, 2,
    4, 1, 0, 7, 5, 1, 9, 9, 3, 7
])

In [51]:
log_reg = LogisticRegression(max_iter=10_000)
log_reg.fit(X_representative_digits, y_representative_digits)
log_reg.score(X_test, y_test)

0.06801007556675064

In [52]:
y_train_propagated = np.empty(len(X_train), dtype=np.int64)
for i in range(k):
    y_train_propagated[kmeans.labels_ == i] = y_representative_digits[i]

In [53]:
log_reg=LogisticRegression()

In [54]:
log_reg.fit(X_train,y_train_propagated)

c:\Users\uzebk\miniconda3\envs\dsenv\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,None
,solver,'lbfgs'
,max_iter,100
,multi_class,'deprecated'


In [55]:
log_reg.score(X_test,y_test)

0.06801007556675064

In [56]:
percentile_closest = 99
X_cluster_dist = X_digits_dist[np.arange(len(X_train)), kmeans.labels_]
for i in range(k):
    in_cluster = (kmeans.labels_ == i)
    cluster_dist = X_cluster_dist[in_cluster]
    cutoff_distance = np.percentile(cluster_dist, percentile_closest)
    above_cutoff = (X_cluster_dist > cutoff_distance)
    X_cluster_dist[in_cluster & above_cutoff] = -1

partially_propagated = (X_cluster_dist != -1)
X_train_partially_propagated = X_train[partially_propagated]
y_train_partially_propagated = y_train_propagated[partially_propagated]

In [57]:
log_reg = LogisticRegression(max_iter=10_000)
log_reg.fit(X_train_partially_propagated, y_train_partially_propagated)
log_reg.score(X_test, y_test)

0.07808564231738035

In [58]:
(y_train_partially_propagated == y_train[partially_propagated]).mean()

np.float64(0.09481481481481481)

In [59]:
from sklearn.cluster import DBSCAN
from sklearn.datasets import make_moons
X, y = make_moons(n_samples=1000, noise=0.05)
dbscan = DBSCAN(eps=0.05, min_samples=5)
dbscan.fit(X)

,eps,0.05
,min_samples,5
,metric,'euclidean'
,metric_params,None
,algorithm,'auto'
,leaf_size,30
,p,None
,n_jobs,None


In [60]:
dbscan.labels_

array([ 0,  1,  1,  1,  0,  0,  2,  2,  0,  0,  3,  2,  1,  1,  0,  0,  1,
        2,  0,  1, -1,  0,  1,  1,  1,  0,  0,  0,  0,  2,  1,  1,  2,  1,
        2, -1,  2, -1, -1,  2,  0,  1, -1,  0,  0,  1,  0,  0,  1, -1,  2,
        0,  0,  0,  0,  1,  1,  1,  0,  1,  1,  1,  0,  1, -1,  1,  1, -1,
       -1,  2,  1,  3,  0,  0,  2,  0,  2,  4,  0,  1,  1,  0,  1, -1, -1,
        1,  3,  0,  0,  1, -1, -1,  0,  0,  0,  1,  1, -1,  0,  1,  3,  2,
        3,  1,  0,  2,  1,  1, -1,  0,  1,  1,  1,  0,  4,  4,  1,  0,  0,
        0,  0,  3,  0,  0,  2, -1,  1,  1,  2,  2,  0,  3,  3,  1,  0,  2,
        1,  0,  1,  1,  4, -1,  0,  0,  1,  0, -1,  0,  0,  0,  3,  1,  2,
        1,  0,  2,  2, -1,  0,  1,  0,  0,  2,  1,  1,  1,  0,  0,  2,  0,
        1,  4,  0,  0,  0,  2,  1,  0, -1,  0,  2, -1,  1,  1,  0,  0,  0,
        0,  4,  0,  0,  0,  1,  1,  4,  0,  2,  1,  0,  1,  1,  1,  3,  2,
        1,  0,  1,  2,  1,  5,  4,  4, -1,  0,  1,  0,  2,  0,  2,  1,  1,
        1,  0,  1,  0,  1

In [61]:
dbscan.core_sample_indices_

array([  0,   2,   3,   4,   5,   6,   7,   8,  10,  11,  12,  13,  14,
        17,  18,  23,  25,  26,  27,  28,  29,  30,  31,  32,  34,  36,
        39,  40,  41,  43,  44,  45,  46,  47,  50,  51,  52,  53,  54,
        56,  57,  58,  59,  60,  61,  62,  63,  65,  66,  69,  70,  72,
        73,  74,  75,  76,  77,  79,  80,  81,  82,  85,  86,  87,  88,
        89,  92,  93,  94,  95,  96,  98,  99, 101, 102, 103, 104, 105,
       106, 107, 109, 110, 111, 112, 113, 114, 115, 116, 117, 119, 120,
       121, 122, 123, 124, 126, 127, 128, 129, 130, 131, 132, 133, 134,
       135, 136, 137, 138, 139, 140, 142, 143, 144, 145, 147, 148, 149,
       152, 154, 155, 156, 158, 159, 161, 162, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 179, 180, 182, 183,
       184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 196, 197,
       198, 199, 200, 201, 202, 203, 204, 205, 207, 208, 211, 213, 214,
       215, 216, 217, 218, 219, 220, 222, 223, 224, 225, 226, 22

In [62]:
dbscan.components_

array([[ 0.66333731, -0.38889783],
       [ 0.32090534,  0.9226726 ],
       [ 0.04828046,  0.97445996],
       ...,
       [ 0.22412789,  0.94162818],
       [ 0.95916037,  0.29769705],
       [-0.93860576,  0.35881082]], shape=(803, 2))

In [63]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=50)
knn.fit(dbscan.components_, dbscan.labels_[dbscan.core_sample_indices_])

,n_neighbors,50
,weights,'uniform'
,algorithm,'auto'
,leaf_size,30
,p,2
,metric,'minkowski'
,metric_params,None
,n_jobs,None


In [64]:
X_new = np.array([[-0.5, 0], [0, 0.5], [1, -0.1], [2, 1]])

In [65]:
knn.predict(X_new)

array([1, 0, 2, 3])

In [66]:
knn.predict_proba(X_new)

array([[0.12, 0.88, 0.  , 0.  , 0.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.3 , 0.  , 0.7 , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.78, 0.18, 0.04, 0.  ]])

In [67]:
y_dist, y_pred_idx = knn.kneighbors(X_new, n_neighbors=1)

In [68]:
y_pred = dbscan.labels_[dbscan.core_sample_indices_][y_pred_idx]

In [69]:
y_pred[y_dist > 0.2] = -1

In [70]:
y_pred.ravel()

array([-1,  0,  2, -1])

In [71]:
from sklearn.mixture import GaussianMixture
gm = GaussianMixture(n_components=3, n_init=10)
gm.fit(X)

c:\Users\uzebk\miniconda3\envs\dsenv\Lib\site-packages\sklearn\cluster\_kmeans.py:1419: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=4.
  warnings.warn(
c:\Users\uzebk\miniconda3\envs\dsenv\Lib\site-packages\sklearn\cluster\_kmeans.py:1419: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=4.
  warnings.warn(
c:\Users\uzebk\miniconda3\envs\dsenv\Lib\site-packages\sklearn\cluster\_kmeans.py:1419: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=4.
  warnings.warn(
c:\Users\uzebk\miniconda3\envs\dsenv\Lib\site-packages\sklearn\cluster\_kmeans.py:1419: UserWarning:

,n_components,3
,covariance_type,'full'
,tol,0.001
,reg_covar,1e-06
,max_iter,100
,n_init,10
,init_params,'kmeans'
,weights_init,None
,means_init,None
,precisions_init,None
,random_state,None


In [72]:
gm.weights_

array([0.20506953, 0.59173117, 0.2031993 ])

In [73]:
gm.means_

array([[ 1.74706985, -0.0615705 ],
       [ 0.49786527,  0.2528441 ],
       [-0.74788751,  0.55820738]])

In [74]:
gm.covariances_

array([[[ 0.05282888,  0.06304343],
        [ 0.06304343,  0.09090408]],

       [[ 0.16810681, -0.1017883 ],
        [-0.1017883 ,  0.28950054]],

       [[ 0.04968797,  0.05991364],
        [ 0.05991364,  0.08820375]]])

In [75]:
gm.converged_

True

In [76]:
gm.n_iter_

16

In [78]:
gm.predict(X)

array([1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 2, 1, 1, 1, 1, 1, 1, 2, 2, 1,
       2, 1, 2, 1, 0, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 0, 1, 1, 1, 2, 2, 1,
       1, 1, 1, 1, 2, 1, 1, 1, 0, 0, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2,
       1, 1, 1, 1, 2, 0, 1, 1, 1, 1, 1, 0, 1, 1, 2, 1, 1, 1, 0, 2, 0, 0,
       0, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 0, 1, 0, 2, 0, 1, 2, 2, 1, 1,
       2, 1, 2, 0, 0, 0, 2, 1, 1, 1, 0, 0, 1, 1, 1, 0, 2, 1, 1, 1, 1, 0,
       0, 2, 1, 1, 2, 1, 1, 2, 0, 1, 0, 0, 2, 1, 1, 1, 1, 1, 0, 2, 1, 2,
       1, 1, 1, 0, 1, 2, 0, 1, 1, 2, 1, 2, 1, 1, 1, 1, 2, 0, 0, 1, 1, 1,
       2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 2, 2, 0, 1, 1, 2,
       0, 2, 1, 1, 0, 1, 1, 1, 2, 1, 2, 0, 0, 0, 1, 1, 2, 1, 1, 1, 1, 1,
       2, 1, 1, 1, 1, 1, 0, 1, 1, 2, 1, 1, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 2, 1,
       1, 2, 2, 2, 0, 1, 1, 2, 1, 1, 1, 0, 0, 0, 1,

In [79]:
gm.predict_proba(X).round(3)

array([[0.   , 1.   , 0.   ],
       [0.   , 0.001, 0.999],
       [0.   , 1.   , 0.   ],
       ...,
       [0.   , 0.   , 1.   ],
       [0.   , 1.   , 0.   ],
       [0.   , 0.   , 1.   ]], shape=(1000, 3))

In [80]:
X_new, y_new = gm.sample(6)

In [81]:
X_new

array([[ 0.31982888,  0.54175244],
       [-0.11370379, -0.1098025 ],
       [ 0.29854951, -0.23149247],
       [ 0.793771  , -0.23606743],
       [ 0.33324881,  0.71633772],
       [ 0.81403024, -0.21208971]])

In [82]:
y_new

array([1, 1, 1, 1, 1, 1])

In [83]:
gm.score_samples(X).round(2)

array([-1.46, -0.03, -1.52, -1.78, -1.58, -1.34, -1.38, -1.49, -1.42,
       -1.56, -1.  , -1.64,  0.02, -1.52, -1.69, -2.2 , -1.86, -1.48,
       -1.53, -0.02, -2.64, -1.35, -0.69, -1.69, -0.28, -1.65, -0.63,
       -2.12, -1.64, -1.54, -2.1 , -2.08, -1.46,  0.09, -1.43, -1.86,
       -1.67, -1.53, -1.7 , -1.54, -1.6 , -0.39, -0.41, -1.33, -1.93,
       -1.81, -1.38, -1.69, -1.57, -2.27, -1.74, -1.71, -0.15, -0.2 ,
       -1.59, -2.12, -1.41, -2.03, -2.28, -1.63, -1.66, -2.23, -1.56,
       -1.48, -2.17,  0.13, -1.83, -1.27, -2.37, -1.5 , -0.26, -0.88,
       -1.57, -1.41, -1.58, -1.7 , -1.55, -0.53, -2.04, -1.41, -0.93,
       -1.53, -1.98, -1.33, -2.78, -0.77, -0.37, -0.77,  0.02, -1.83,
       -1.88, -2.06, -1.55, -1.45, -2.28, -2.22, -0.47, -1.91, -1.72,
       -1.69, -2.99, -1.57, -0.47, -0.17, -0.1 , -1.57, -0.13, -0.46,
       -1.23, -1.63, -0.17, -2.09, -0.41, -1.93,  0.05, -0.29, -0.21,
       -1.77, -1.83, -1.54,  0.02, -0.37, -1.69, -2.13, -1.65, -1.82,
       -0.13, -1.68,

In [84]:
densities = gm.score_samples(X)
density_threshold = np.percentile(densities, 2)
anomalies = X[densities < density_threshold]

In [85]:
gm.bic(X)

np.float64(2751.752423668187)

In [86]:
gm.aic(X)

np.float64(2668.3205839254906)

In [87]:
from sklearn.mixture import BayesianGaussianMixture
bgm = BayesianGaussianMixture(n_components=10, n_init=10, random_state=42)
bgm.fit(X)
bgm.weights_.round(2)

c:\Users\uzebk\miniconda3\envs\dsenv\Lib\site-packages\sklearn\cluster\_kmeans.py:1419: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=4.
  warnings.warn(
c:\Users\uzebk\miniconda3\envs\dsenv\Lib\site-packages\sklearn\cluster\_kmeans.py:1419: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=4.
  warnings.warn(
c:\Users\uzebk\miniconda3\envs\dsenv\Lib\site-packages\sklearn\cluster\_kmeans.py:1419: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=4.
  warnings.warn(
c:\Users\uzebk\miniconda3\envs\dsenv\Lib\site-packages\sklearn\cluster\_kmeans.py:1419: UserWarning:

array([0.15, 0.2 , 0.14, 0.14, 0.12, 0.  , 0.11, 0.15, 0.  , 0.  ])